# Generated by Django 2.0 on 2018-07-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select', models.BigIntegerField(verbose_name='Select:')),
            ],
        ),
    ]
