# Generated by Django 2.0 on 2018-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0002_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='Select',
            field=models.BigIntegerField(verbose_name='Select'),
        ),
    ]
