# Generated by Django 2.0 on 2018-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0003_auto_20180703_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='Select',
        ),
        migrations.AddField(
            model_name='values',
            name='choice',
            field=models.CharField(blank=True, choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5')], max_length=2, verbose_name='Select'),
        ),
    ]
