# Generated by Django 2.0 on 2018-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0004_auto_20180703_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='choice',
            field=models.CharField(blank=True, max_length=2, verbose_name='Select'),
        ),
    ]
