# Generated by Django 2.0 on 2018-07-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0005_auto_20180703_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Values',
        ),
    ]
