# Generated by Django 2.0 on 2018-07-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0006_delete_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=2, verbose_name='Select')),
            ],
        ),
    ]
