# Generated by Django 2.0 on 2018-07-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0007_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
