# Generated by Django 2.0 on 2018-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0008_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='choice',
        ),
        migrations.AddField(
            model_name='values',
            name='SN',
            field=models.CharField(blank=True, max_length=10, verbose_name='StudentNumber'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice1',
            field=models.CharField(blank=True, max_length=2, verbose_name='V1'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice10',
            field=models.CharField(blank=True, max_length=2, verbose_name='V10'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice11',
            field=models.CharField(blank=True, max_length=2, verbose_name='V11'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice12',
            field=models.CharField(blank=True, max_length=2, verbose_name='V12'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice13',
            field=models.CharField(blank=True, max_length=2, verbose_name='V13'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice14',
            field=models.CharField(blank=True, max_length=2, verbose_name='V14'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice15',
            field=models.CharField(blank=True, max_length=2, verbose_name='V15'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice16',
            field=models.CharField(blank=True, max_length=2, verbose_name='V16'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice17',
            field=models.CharField(blank=True, max_length=2, verbose_name='V17'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice2',
            field=models.CharField(blank=True, max_length=2, verbose_name='V2'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice3',
            field=models.CharField(blank=True, max_length=2, verbose_name='V3'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice4',
            field=models.CharField(blank=True, max_length=2, verbose_name='V4'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice5',
            field=models.CharField(blank=True, max_length=2, verbose_name='V5'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice6',
            field=models.CharField(blank=True, max_length=2, verbose_name='V6'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice7',
            field=models.CharField(blank=True, max_length=2, verbose_name='V7'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice8',
            field=models.CharField(blank=True, max_length=2, verbose_name='V8'),
        ),
        migrations.AddField(
            model_name='values',
            name='choice9',
            field=models.CharField(blank=True, max_length=2, verbose_name='V9'),
        ),
    ]
