# Generated by Django 2.0 on 2018-07-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABCquestionnaire', '0010_auto_20180706_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='SN',
        ),
    ]
